---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
data:
  config.yaml: |
    server:
{{- toYaml .Values.headplane.config.server | nindent 6 }}
      cookie_secret: {{ include "headplane.cookieSecret" . | quote }}
    headscale:
{{- toYaml .Values.headplane.config.headscale | nindent 6 }}
    integration:
{{- toYaml .Values.headplane.config.integration | nindent 6 }}
# only add oidc if .Values.headplane.config.oidc is set
{{- if .Values.headplane.config.oidc }}
    oidc:
{{- toYaml .Values.headplane.config.oidc | nindent 6 }}
      client_secret: "secret"
      headscale_api_key: "secret"
{{- end }}
