---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
data:
  config.yaml: |
    server:
{{- toYaml .Values.headplane.config.server | nindent 6 }}
      cookie_secret: {{ include "headplane.cookieSecret" . | quote }}
    headscale:
{{- toYaml .Values.headplane.config.headscale | nindent 6 }}
    integration:
{{- toYaml .Values.headplane.config.integration | nindent 6 }}
# only add oidc if .Values.headplane.config.oidc is set
{{- if .Values.headplane.config.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headplane.config.oidc.issuer | quote }}
      disable_api_key_login: {{ .Values.headplane.config.oidc.disable_api_key_login | quote }}
      token_endpoint_auth_method: {{ .Values.headplane.config.oidc.token_endpoint_auth_method | quote }}
      redirect_uri: {{ .Values.headplane.config.oidc.redirect_uri | quote }}
      client_id: {{ .Values.headplane.config.oidc.client_id | quote }}
{{- end }}
