{{- if .Values.headplane.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headplane.secret.name }}
  {{- with .Values.headplane.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  #only add if oidc is set
  {{- if .Values.headplane.config.oidc }}
  {{- if .Values.headplane.secret.oidc.client_secret}}
  HEADPLANE_OIDC__CLIENT_SECRET: {{ .Values.headplane.secret.oidc.client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.headplane.secret.oidc.client_id }}
  HEADPLANE_OIDC__CLIENT_ID: {{ .Values.headplane.secret.oidc.client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.headplane.secret.oidc.headscale_api_key }}
  HEADPLANE_OIDC__HEADSCALE_API_KEY: {{ .Values.headplane.secret.oidc.headscale_api_key | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not (lookup "v1" "Secret" .Release.Namespace .Values.headplane.secret.name) }}
  HEADPLANE_SERVER__COOKIE_SECRET: {{ include "headplane.cookieSecret" . | b64enc | quote }}
  {{- end }}
{{- end }}
